execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:3,max:3}}}}} run scoreboard players set abilityusep3 booleans 1
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:3,max:3}}}}} run scoreboard players set abilityusep4 booleans 2

execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:3,max:3}}}}} run execute if score slot9isatk booleans matches 1.. run scoreboard players operation cooldown slot9 = deuceCD abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:3,max:3}}}}} run execute if score slot10isatk booleans matches 1.. run scoreboard players operation cooldown slot10 = deuceCD abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:3,max:3}}}}} run execute if score slot11isatk booleans matches 1.. run scoreboard players operation cooldown slot11 = deuceCD abilityStats

execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:3,max:3}}}}} run execute if score slot13isatk booleans matches 1.. run scoreboard players operation cooldown slot13 = deuceCD abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:3,max:3}}}}} run execute if score slot14isatk booleans matches 1.. run scoreboard players operation cooldown slot14 = deuceCD abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:3,max:3}}}}} run execute if score slot15isatk booleans matches 1.. run scoreboard players operation cooldown slot15 = deuceCD abilityStats
scoreboard players set burn burn2 1
scoreboard players set abilitynumber2 abilities 3
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:3,max:3}}}}} run function ch:abilitygivetargetsp3
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:3,max:3}}}}} run function ch:abilitygivetargetsp4