execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} if score durationSlot9 taunt < golemTaunt abilityStats run execute if score slot9isatk booleans matches 1 run scoreboard players operation durationSlot9 taunt = golemTaunt abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} if score durationSlot10 taunt < golemTaunt abilityStats run execute if score slot10isatk booleans matches 1 run scoreboard players operation durationSlot10 taunt = golemTaunt abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} if score durationSlot11 taunt < golemTaunt abilityStats run execute if score slot11isatk booleans matches 1 run scoreboard players operation durationSlot11 taunt = golemTaunt abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run tellraw @a[tag=game2] ["",{"selector":"@p[tag=p3]"}," used Get Behind Me!"]
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot9isatk booleans matches 1 run scoreboard players operation cooldown slot9 = golemCD abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot10isatk booleans matches 1 run scoreboard players operation cooldown slot10 = golemCD abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot11isatk booleans matches 1 run scoreboard players operation cooldown slot11 = golemCD abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run scoreboard players set burn burn2 1
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run scoreboard players set abilityusep3 booleans 1
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot9isatk booleans matches 1 run execute at @n[type=armor_stand,name=slot9] run particle block_crumble{block_state:"minecraft:deepslate_emerald_ore"} ~ ~1 ~ 0.9 0.9 0.9 0.1 10000
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot10isatk booleans matches 1 run execute at @n[type=armor_stand,name=slot10] run particle block_crumble{block_state:"minecraft:deepslate_emerald_ore"} ~ ~1 ~ 0.9 0.9 0.9 0.1 10000
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot11isatk booleans matches 1 run execute at @n[type=armor_stand,name=slot11] run particle block_crumble{block_state:"minecraft:deepslate_emerald_ore"} ~ ~1 ~ 0.9 0.9 0.9 0.1 10000
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run function ch:turnend
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run effect clear @a[tag=p3] fire_resistance

execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} if score durationSlot13 taunt < golemTaunt abilityStats run execute if score slot13isatk booleans matches 1 run scoreboard players operation durationSlot13 taunt = golemTaunt abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} if score durationSlot14 taunt < golemTaunt abilityStats run execute if score slot14isatk booleans matches 1 run scoreboard players operation durationSlot14 taunt = golemTaunt abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} if score durationSlot15 taunt < golemTaunt abilityStats run execute if score slot15isatk booleans matches 1 run scoreboard players operation durationSlot15 taunt = golemTaunt abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run tellraw @a[tag=game2] ["",{"selector":"@p[tag=p4]"}," used Get Behind Me!"]
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot13isatk booleans matches 1 run scoreboard players operation cooldown slot13 = golemCD abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot14isatk booleans matches 1 run scoreboard players operation cooldown slot14 = golemCD abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot15isatk booleans matches 1 run scoreboard players operation cooldown slot15 = golemCD abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run scoreboard players set burn burn2 1
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run scoreboard players set abilityusep4 booleans 1
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot13isatk booleans matches 1 run execute at @n[type=armor_stand,name=slot13] run particle block_crumble{block_state:"minecraft:deepslate_emerald_ore"} ~ ~1 ~ 0.9 0.9 0.9 0.1 10000
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot14isatk booleans matches 1 run execute at @n[type=armor_stand,name=slot14] run particle block_crumble{block_state:"minecraft:deepslate_emerald_ore"} ~ ~1 ~ 0.9 0.9 0.9 0.1 10000
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run execute if score slot15isatk booleans matches 1 run execute at @n[type=armor_stand,name=slot15] run particle block_crumble{block_state:"minecraft:deepslate_emerald_ore"} ~ ~1 ~ 0.9 0.9 0.9 0.1 10000
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run function ch:turnend
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:15,max:15}}}}} run effect clear @a[tag=p4] fire_resistance

