execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot13 matches 0 if score blizzardSpDebuffDuration spellStats > durationSlot13 speedDebuffs run scoreboard players operation durationSlot13 speedDebuffs = blizzardSpDebuffDuration spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot14 matches 0 if score blizzardSpDebuffDuration spellStats > durationSlot14 speedDebuffs run scoreboard players operation durationSlot14 speedDebuffs = blizzardSpDebuffDuration spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot15 matches 0 if score blizzardSpDebuffDuration spellStats > durationSlot15 speedDebuffs run scoreboard players operation durationSlot15 speedDebuffs = blizzardSpDebuffDuration spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot16 matches 0 if score blizzardSpDebuffDuration spellStats > durationSlot16 speedDebuffs run scoreboard players operation durationSlot16 speedDebuffs = blizzardSpDebuffDuration spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot13 matches 0 run scoreboard players operation speedDebuffSlot13 speedDebuffs += blizzardSpDebuff spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot14 matches 0 run scoreboard players operation speedDebuffSlot14 speedDebuffs += blizzardSpDebuff spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot15 matches 0 run scoreboard players operation speedDebuffSlot15 speedDebuffs += blizzardSpDebuff spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot16 matches 0 run scoreboard players operation speedDebuffSlot16 speedDebuffs += blizzardSpDebuff spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot13 matches 0 run scoreboard players operation speed slot13 -= blizzardSpDebuff spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot14 matches 0 run scoreboard players operation speed slot14 -= blizzardSpDebuff spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot15 matches 0 run scoreboard players operation speed slot15 -= blizzardSpDebuff spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot16 matches 0 run scoreboard players operation speed slot16 -= blizzardSpDebuff spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmg2 saves = blizzard spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmg2 saves += spellbuffsp3 spells
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot13 saves = spellDmg2 saves
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot14 saves = spellDmg2 saves
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot15 saves = spellDmg2 saves
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot16 saves = spellDmg2 saves
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot13 saves += marks slot13
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot14 saves += marks slot14
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot15 saves += marks slot15
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot16 saves += marks slot16
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot13 saves /= atkmultiplier slot13
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot14 saves /= atkmultiplier slot14
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot15 saves /= atkmultiplier slot15
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgSlot16 saves /= atkmultiplier slot16
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot13 matches 0 run scoreboard players operation shield slot13 -= spellDmgSlot13 saves
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot14 matches 0 run scoreboard players operation shield slot14 -= spellDmgSlot14 saves
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot15 matches 0 run scoreboard players operation shield slot15 -= spellDmgSlot15 saves
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot16 matches 0 run scoreboard players operation shield slot16 -= spellDmgSlot16 saves
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot13 matches 0 if score shield slot13 matches ..0 run scoreboard players operation slot13 hp += shield slot13
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot14 matches 0 if score shield slot14 matches ..0 run scoreboard players operation slot14 hp += shield slot14
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot15 matches 0 if score shield slot15 matches ..0 run scoreboard players operation slot15 hp += shield slot15
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot16 matches 0 if score shield slot16 matches ..0 run scoreboard players operation slot16 hp += shield slot16
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score shield slot13 matches ..0 run scoreboard players set shield slot13 0
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score shield slot14 matches ..0 run scoreboard players set shield slot14 0
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score shield slot15 matches ..0 run scoreboard players set shield slot15 0
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score shield slot16 matches ..0 run scoreboard players set shield slot16 0
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} at @e[name=slot13] run particle minecraft:snowflake ~ ~1 ~ 0.9 0.9 0.9 0.5 500
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} at @e[name=slot14] run particle minecraft:snowflake ~ ~1 ~ 0.9 0.9 0.9 0.5 500
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} at @e[name=slot15] run particle minecraft:snowflake ~ ~1 ~ 0.9 0.9 0.9 0.5 500
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} at @e[name=slot16] run particle minecraft:snowflake ~ ~1 ~ 0.9 0.9 0.9 0.5 500
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation blizzardCooldown player3spells = blizzardCD spellStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot13 matches 1.. run function ch:wardslot13
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot14 matches 1.. run function ch:wardslot14
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot15 matches 1.. run function ch:wardslot15
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot16 matches 1.. run function ch:wardslot16
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run tellraw @a[tag=game2] ["",{"selector":"@p[tag=p3]"}," used Blizzard!"]
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players set attackIsOngoingGame2 booleans 0
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run clear @a[tag=p3]
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players set spellbuffsp3 spells 0
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run effect clear @a[tag=p3] infested

execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot9 matches 0 if score blizzardSpDebuffDuration spellStats > durationSlot9 speedDebuffs run scoreboard players operation durationSlot9 speedDebuffs = blizzardSpDebuffDuration spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot10 matches 0 if score blizzardSpDebuffDuration spellStats > durationSlot10 speedDebuffs run scoreboard players operation durationSlot10 speedDebuffs = blizzardSpDebuffDuration spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot11 matches 0 if score blizzardSpDebuffDuration spellStats > durationSlot11 speedDebuffs run scoreboard players operation durationSlot11 speedDebuffs = blizzardSpDebuffDuration spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot12 matches 0 if score blizzardSpDebuffDuration spellStats > durationSlot12 speedDebuffs run scoreboard players operation durationSlot12 speedDebuffs = blizzardSpDebuffDuration spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot9 matches 0 run scoreboard players operation speedDebuffslot9 speedDebuffs += blizzardSpDebuff spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot10 matches 0 run scoreboard players operation speedDebuffslot10 speedDebuffs += blizzardSpDebuff spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot11 matches 0 run scoreboard players operation speedDebuffslot11 speedDebuffs += blizzardSpDebuff spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot12 matches 0 run scoreboard players operation speedDebuffslot12 speedDebuffs += blizzardSpDebuff spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot9 matches 0 run scoreboard players operation speed slot9 -= blizzardSpDebuff spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot10 matches 0 run scoreboard players operation speed slot10 -= blizzardSpDebuff spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot11 matches 0 run scoreboard players operation speed slot11 -= blizzardSpDebuff spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot12 matches 0 run scoreboard players operation speed slot12 -= blizzardSpDebuff spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmg2 saves = blizzard spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmg2 saves += spellbuffsp4 spells
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot9 saves = spellDmg2 saves
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot10 saves = spellDmg2 saves
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot11 saves = spellDmg2 saves
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot12 saves = spellDmg2 saves
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot9 saves += marks slot9
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot10 saves += marks slot10
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot11 saves += marks slot11
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot12 saves += marks slot12
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot9 saves /= atkmultiplier slot9
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot10 saves /= atkmultiplier slot10
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot11 saves /= atkmultiplier slot11
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation spellDmgslot12 saves /= atkmultiplier slot12
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot9 matches 0 run scoreboard players operation shield slot9 -= spellDmgslot9 saves
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot10 matches 0 run scoreboard players operation shield slot10 -= spellDmgslot10 saves
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot11 matches 0 run scoreboard players operation shield slot11 -= spellDmgslot11 saves
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot12 matches 0 run scoreboard players operation shield slot12 -= spellDmgslot12 saves
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot9 matches 0 if score shield slot9 matches ..0 run scoreboard players operation slot9 hp += shield slot9
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot10 matches 0 if score shield slot10 matches ..0 run scoreboard players operation slot10 hp += shield slot10
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot11 matches 0 if score shield slot11 matches ..0 run scoreboard players operation slot11 hp += shield slot11
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score ward slot12 matches 0 if score shield slot12 matches ..0 run scoreboard players operation slot12 hp += shield slot12
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score shield slot9 matches ..0 run scoreboard players set shield slot9 0
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score shield slot10 matches ..0 run scoreboard players set shield slot10 0
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score shield slot11 matches ..0 run scoreboard players set shield slot11 0
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run execute if score shield slot12 matches ..0 run scoreboard players set shield slot12 0
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} at @e[name=slot9] run particle minecraft:snowflake ~ ~1 ~ 0.9 0.9 0.9 0.5 500
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} at @e[name=slot10] run particle minecraft:snowflake ~ ~1 ~ 0.9 0.9 0.9 0.5 500
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} at @e[name=slot11] run particle minecraft:snowflake ~ ~1 ~ 0.9 0.9 0.9 0.5 500
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} at @e[name=slot12] run particle minecraft:snowflake ~ ~1 ~ 0.9 0.9 0.9 0.5 500
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players operation blizzardCooldown player4spells = blizzardCD spellStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot9 matches 1.. run function ch:wardslot9
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot10 matches 1.. run function ch:wardslot10
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot11 matches 1.. run function ch:wardslot11
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} if score ward slot12 matches 1.. run function ch:wardslot12
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run tellraw @a[tag=game2] ["",{"selector":"@p[tag=p4]"}," used Blizzard!"]
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run function ch:spellphasep3
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run clear @a[tag=p4]
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run scoreboard players set spellbuffsp4 spells 0
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:infested":{amplifier:{min:20,max:20}}}}} run effect clear @a[tag=p4] infested




