#player3
clear @p[tag=p3]
execute if score slot13 hp matches 1.. run give @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 5",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:1,show_particles:0b}]}]}] 5
execute if score slot14 hp matches 1.. run give @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 6",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:2,show_particles:0b}]}]}] 6
execute if score slot15 hp matches 1.. run give @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 7",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:3,show_particles:0b}]}]}] 7
execute if score slot16 hp matches 1.. run give @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 8",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:4,show_particles:0b}]}]}] 8
effect clear @p[tag=p3] minecraft:conduit_power

execute if score slot9isatk booleans matches 1 if score durationSlot13-9 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 5",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:1,show_particles:0b}]}]}] 5
execute if score slot9isatk booleans matches 1 if score durationSlot14-9 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 6",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:2,show_particles:0b}]}]}] 6
execute if score slot9isatk booleans matches 1 if score durationSlot15-9 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 7",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:3,show_particles:0b}]}]}] 7
execute if score slot9isatk booleans matches 1 if score durationSlot16-9 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 8",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:4,show_particles:0b}]}]}] 8

execute if score slot10isatk booleans matches 1 if score durationSlot13-10 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 5",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:1,show_particles:0b}]}]}] 5
execute if score slot10isatk booleans matches 1 if score durationSlot14-10 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 6",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:2,show_particles:0b}]}]}] 6
execute if score slot10isatk booleans matches 1 if score durationSlot15-10 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 7",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:3,show_particles:0b}]}]}] 7
execute if score slot10isatk booleans matches 1 if score durationSlot16-10 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 8",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:4,show_particles:0b}]}]}] 8

execute if score slot11isatk booleans matches 1 if score durationSlot13-11 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 5",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:1,show_particles:0b}]}]}] 5
execute if score slot11isatk booleans matches 1 if score durationSlot14-11 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 6",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:2,show_particles:0b}]}]}] 6
execute if score slot11isatk booleans matches 1 if score durationSlot15-11 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 7",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:3,show_particles:0b}]}]}] 7
execute if score slot11isatk booleans matches 1 if score durationSlot16-11 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 8",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:4,show_particles:0b}]}]}] 8

execute if score slot12isatk booleans matches 1 if score durationSlot13-12 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 5",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:1,show_particles:0b}]}]}] 5
execute if score slot12isatk booleans matches 1 if score durationSlot14-12 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 6",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:2,show_particles:0b}]}]}] 6
execute if score slot12isatk booleans matches 1 if score durationSlot15-12 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 7",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:3,show_particles:0b}]}]}] 7
execute if score slot12isatk booleans matches 1 if score durationSlot16-12 fear matches 1.. run clear @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 8",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:4,show_particles:0b}]}]}] 8


execute if score durationSlot13 taunt matches 1.. run clear @p[tag=p3]
execute if score durationSlot13 taunt matches 1.. run give @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 5",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:1,show_particles:0b}]}]}] 5
execute if score durationSlot14 taunt matches 1.. run clear @p[tag=p3]
execute if score durationSlot14 taunt matches 1.. run give @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 6",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:2,show_particles:0b}]}]}] 6
execute if score durationSlot15 taunt matches 1.. run clear @p[tag=p3]
execute if score durationSlot15 taunt matches 1.. run give @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 7",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:3,show_particles:0b}]}]}] 7
execute if score durationSlot16 taunt matches 1.. run clear @p[tag=p3]
execute if score durationSlot16 taunt matches 1.. run give @p[tag=p3] minecraft:target[minecraft:custom_name="Attack Slot 8",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:conduit_power,duration:1,amplifier:4,show_particles:0b}]}]}] 8