execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithDmgBuffDuration abilityStats > buffDurationSlot9 atkmodifiers run scoreboard players operation buffDurationSlot9 atkmodifiers = lillithDmgBuffDuration abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithDmgBuffDuration abilityStats > buffDurationSlot10 atkmodifiers run scoreboard players operation buffDurationSlot10 atkmodifiers = lillithDmgBuffDuration abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithDmgBuffDuration abilityStats > buffDurationSlot11 atkmodifiers run scoreboard players operation buffDurationSlot11 atkmodifiers = lillithDmgBuffDuration abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithDmgBuffDuration abilityStats > buffDurationSlot12 atkmodifiers run scoreboard players operation buffDurationSlot12 atkmodifiers = lillithDmgBuffDuration abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithSelfDmgBuffDuration abilityStats > buffDurationSlot9 atkmodifiers if score slot9isatk booleans matches 1 run scoreboard players operation buffDurationSlot9 atkmodifiers = lillithSelfDmgBuffDuration abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithSelfDmgBuffDuration abilityStats > buffDurationSlot10 atkmodifiers if score slot10isatk booleans matches 1 run scoreboard players operation buffDurationSlot10 atkmodifiers = lillithSelfDmgBuffDuration abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithSelfDmgBuffDuration abilityStats > buffDurationSlot11 atkmodifiers if score slot11isatk booleans matches 1 run scoreboard players operation buffDurationSlot11 atkmodifiers = lillithSelfDmgBuffDuration abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players operation attackBuffSlot9 atkmodifiers += lillithDmgBuff abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players operation attackBuffSlot10 atkmodifiers += lillithDmgBuff abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players operation attackBuffSlot11 atkmodifiers += lillithDmgBuff abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players operation attackBuffSlot12 atkmodifiers += lillithDmgBuff abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score slot9isatk booleans matches 1 run scoreboard players operation cooldown slot9 = lillithCD abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score slot10isatk booleans matches 1 run scoreboard players operation cooldown slot10 = lillithCD abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score slot11isatk booleans matches 1 run scoreboard players operation cooldown slot11 = lillithCD abilityStats
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run execute at @n[type=armor_stand,name=slot9] run particle minecraft:sculk_soul ~ ~1 ~ 0.9 0.9 0.9 0 100
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run execute at @n[type=armor_stand,name=slot10] run particle minecraft:sculk_soul ~ ~1 ~ 0.9 0.9 0.9 0 100
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run execute at @n[type=armor_stand,name=slot11] run particle minecraft:sculk_soul ~ ~1 ~ 0.9 0.9 0.9 0 100
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run execute at @n[type=armor_stand,name=slot12] run particle minecraft:sculk_soul ~ ~1 ~ 0.9 0.9 0.9 0 100
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players set burn2 burn 1
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players set abilityusep3 booleans 1
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run function ch:turnend
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run tellraw @a[tag=game2] ["",{"selector":"@p[tag=p3]"}," used Dark Ritual!"]
execute as @a[tag=p3] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run effect clear @a[tag=p3] fire_resistance

#player 2
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithDmgBuffDuration abilityStats > buffDurationSlot13 atkmodifiers run scoreboard players operation buffDurationSlot13 atkmodifiers = lillithDmgBuffDuration abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithDmgBuffDuration abilityStats > buffDurationSlot14 atkmodifiers run scoreboard players operation buffDurationSlot14 atkmodifiers = lillithDmgBuffDuration abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithDmgBuffDuration abilityStats > buffDurationSlot15 atkmodifiers run scoreboard players operation buffDurationSlot15 atkmodifiers = lillithDmgBuffDuration abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithDmgBuffDuration abilityStats > buffDurationSlot16 atkmodifiers run scoreboard players operation buffDurationSlot16 atkmodifiers = lillithDmgBuffDuration abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithDmgBuffDuration abilityStats > buffDurationSlot13 atkmodifiers if score slot13isatk booleans matches 1 run scoreboard players operation buffDurationSlot13 atkmodifiers = lillithSelfDmgBuffDuration abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithDmgBuffDuration abilityStats > buffDurationSlot14 atkmodifiers if score slot14isatk booleans matches 1 run scoreboard players operation buffDurationSlot14 atkmodifiers = lillithSelfDmgBuffDuration abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score lillithDmgBuffDuration abilityStats > buffDurationSlot15 atkmodifiers if score slot15isatk booleans matches 1 run scoreboard players operation buffDurationSlot15 atkmodifiers = lillithSelfDmgBuffDuration abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players operation attackBuffSlot13 atkmodifiers += lillithDmgBuff abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players operation attackBuffSlot14 atkmodifiers += lillithDmgBuff abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players operation attackBuffSlot15 atkmodifiers += lillithDmgBuff abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players operation attackBuffSlot16 atkmodifiers += lillithDmgBuff abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score slot13isatk booleans matches 1 run scoreboard players operation cooldown slot13 = lillithCD abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score slot14isatk booleans matches 1 run scoreboard players operation cooldown slot14 = lillithCD abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} if score slot15isatk booleans matches 1 run scoreboard players operation cooldown slot15 = lillithCD abilityStats
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run execute at @n[type=armor_stand,name=slot13] run particle minecraft:sculk_soul ~ ~1 ~ 0.9 0.9 0.9 0 100
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run execute at @n[type=armor_stand,name=slot14] run particle minecraft:sculk_soul ~ ~1 ~ 0.9 0.9 0.9 0 100
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run execute at @n[type=armor_stand,name=slot15] run particle minecraft:sculk_soul ~ ~1 ~ 0.9 0.9 0.9 0 100
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run execute at @n[type=armor_stand,name=slot16] run particle minecraft:sculk_soul ~ ~1 ~ 0.9 0.9 0.9 0 100

execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players set burn2 burn 1
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run scoreboard players set abilityusep4 booleans 1
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run function ch:turnend
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run tellraw @a[tag=game2] ["",{"selector":"@p[tag=p4]"}," used Dark Ritual!"]
execute as @a[tag=p4] if predicate {condition:"minecraft:entity_properties",entity:"this",predicate:{effects:{"minecraft:fire_resistance":{amplifier:{min:21,max:21}}}}} run effect clear @a[tag=p4] fire_resistance





