clear @p[tag=p4]
effect clear @p[tag=p4]
execute if score slot9 hp matches 1.. run give @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 1",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:1,show_particles:0b}]}]}] 1
execute if score slot10 hp matches 1.. run give @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 2",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:2,show_particles:0b}]}]}] 2
execute if score slot11 hp matches 1.. run give @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 3",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:3,show_particles:0b}]}]}] 3
execute if score slot12 hp matches 1.. run give @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 4",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:4,show_particles:0b}]}]}] 4

execute if score slot13isatk booleans matches 1 if score durationSlot9-13 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 1",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:1,show_particles:0b}]}]}] 1
execute if score slot13isatk booleans matches 1 if score durationSlot10-13 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 2",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:2,show_particles:0b}]}]}] 2
execute if score slot13isatk booleans matches 1 if score durationSlot11-13 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 3",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:3,show_particles:0b}]}]}] 3
execute if score slot13isatk booleans matches 1 if score durationSlot12-13 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 4",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:4,show_particles:0b}]}]}] 4

execute if score slot14isatk booleans matches 1 if score durationSlot9-14 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 1",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:1,show_particles:0b}]}]}] 1
execute if score slot14isatk booleans matches 1 if score durationSlot10-14 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 2",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:2,show_particles:0b}]}]}] 2
execute if score slot14isatk booleans matches 1 if score durationSlot11-14 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 3",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:3,show_particles:0b}]}]}] 3
execute if score slot14isatk booleans matches 1 if score durationSlot12-14 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 4",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:4,show_particles:0b}]}]}] 4

execute if score slot15isatk booleans matches 1 if score durationSlot9-15 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 1",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:1,show_particles:0b}]}]}] 1
execute if score slot15isatk booleans matches 1 if score durationSlot10-15 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 2",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:2,show_particles:0b}]}]}] 2
execute if score slot15isatk booleans matches 1 if score durationSlot11-15 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 3",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:3,show_particles:0b}]}]}] 3
execute if score slot15isatk booleans matches 1 if score durationSlot12-15 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 4",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:4,show_particles:0b}]}]}] 4

execute if score slot16isatk booleans matches 1 if score durationSlot9-16 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 1",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:1,show_particles:0b}]}]}] 1
execute if score slot16isatk booleans matches 1 if score durationSlot10-16 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 2",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:2,show_particles:0b}]}]}] 2
execute if score slot16isatk booleans matches 1 if score durationSlot11-16 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 3",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:3,show_particles:0b}]}]}] 3
execute if score slot16isatk booleans matches 1 if score durationSlot12-16 fear matches 1.. run clear @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 4",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:4,show_particles:0b}]}]}] 4

execute if score durationSlot9 taunt matches 1.. run clear @p[tag=p4]
execute if score durationSlot9 taunt matches 1.. run give @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 1",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:1,show_particles:0b}]}]}] 1
execute if score durationSlot10 taunt matches 1.. run clear @p[tag=p4]
execute if score durationSlot10 taunt matches 1.. run give @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 2",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:2,show_particles:0b}]}]}] 2
execute if score durationSlot11 taunt matches 1.. run clear @p[tag=p4]
execute if score durationSlot11 taunt matches 1.. run give @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 3",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:3,show_particles:0b}]}]}] 3
execute if score durationSlot12 taunt matches 1.. run clear @p[tag=p4]
execute if score durationSlot12 taunt matches 1.. run give @p[tag=p4] minecraft:target[minecraft:custom_name="Target Slot 4",food={can_always_eat:1b,nutrition:1,saturation:1},consumable={consume_seconds:0.1,animation:none,sound:"minecraft:entity.player.attack.sweep",has_consume_particles:0b,on_consume_effects:[{type:apply_effects,effects:[{id:strength,duration:1,amplifier:4,show_particles:0b}]}]}] 4